import {
  Backpack,
  Baby,
  Bike,
  BookOpen,
  Briefcase,
  Camera,
  Car,
  Cpu,
  Crown,
  Diamond,
  Drill,
  Flame,
  Flower2,
  FolderTree,
  Gamepad2,
  Gift,
  Hammer,
  Headphones,
  HeartPulse,
  Home,
  Laptop,
  Lightbulb,
  Monitor,
  PawPrint,
  Phone,
  Refrigerator,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Speaker,
  Star,
  Truck,
  Tv,
  Utensils,
  Watch,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Registro acotado de iconos lucide soportados para categorias.
 * Limita el bundle (vs. importar `* as Icons`) y mantiene un set
 * coherente para administradores. Si el nombre no esta en la lista,
 * el resolver cae a FolderTree.
 */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  Backpack,
  Baby,
  Bike,
  BookOpen,
  Briefcase,
  Camera,
  Car,
  Cpu,
  Crown,
  Diamond,
  Drill,
  Flame,
  Flower2,
  FolderTree,
  Gamepad2,
  Gift,
  Hammer,
  Headphones,
  HeartPulse,
  Home,
  Laptop,
  Lightbulb,
  Monitor,
  PawPrint,
  Phone,
  Refrigerator,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Speaker,
  Star,
  Truck,
  Tv,
  Utensils,
  Watch,
  Wrench,
  Zap,
};

export function resolveCategoryIcon(name?: string | null): LucideIcon {
  if (!name) return FolderTree;
  return CATEGORY_ICONS[name] ?? FolderTree;
}

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS).sort();
