/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminReportesRouteImport } from './routes/admin/reportes'
import { Route as AdminProductosRouteImport } from './routes/admin/productos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminMarcasRouteImport } from './routes/admin/marcas'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInventarioRouteImport } from './routes/admin/inventario'
import { Route as AdminCuponesRouteImport } from './routes/admin/cupones'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminProductosIndexRouteImport } from './routes/admin/productos/index'
import { Route as AdminProductosNuevoRouteImport } from './routes/admin/productos/nuevo'
import { Route as AdminProductosIdRouteImport } from './routes/admin/productos/$id'

const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponesRoute = AdminCuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosIndexRoute = AdminProductosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductosRoute,
} as any)
const AdminProductosNuevoRoute = AdminProductosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AdminProductosRoute,
} as any)
const AdminProductosIdRoute = AdminProductosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRouteWithChildren
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/productos/$id': typeof AdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/productos/$id': typeof AdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos': typeof AdminProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRouteWithChildren
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/productos/$id': typeof AdminProductosIdRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/cupones'
    | '/admin/inventario'
    | '/admin/login'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/producto/$id'
    | '/admin/'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/cupones'
    | '/admin/inventario'
    | '/admin/login'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/producto/$id'
    | '/admin'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/productos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrito'
    | '/catalogo'
    | '/contacto'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/cupones'
    | '/admin/inventario'
    | '/admin/login'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/producto/$id'
    | '/admin/'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupones': {
      id: '/admin/cupones'
      path: '/cupones'
      fullPath: '/admin/cupones'
      preLoaderRoute: typeof AdminCuponesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/': {
      id: '/admin/productos/'
      path: '/'
      fullPath: '/admin/productos/'
      preLoaderRoute: typeof AdminProductosIndexRouteImport
      parentRoute: typeof AdminProductosRoute
    }
    '/admin/productos/nuevo': {
      id: '/admin/productos/nuevo'
      path: '/nuevo'
      fullPath: '/admin/productos/nuevo'
      preLoaderRoute: typeof AdminProductosNuevoRouteImport
      parentRoute: typeof AdminProductosRoute
    }
    '/admin/productos/$id': {
      id: '/admin/productos/$id'
      path: '/$id'
      fullPath: '/admin/productos/$id'
      preLoaderRoute: typeof AdminProductosIdRouteImport
      parentRoute: typeof AdminProductosRoute
    }
  }
}

interface AdminProductosRouteChildren {
  AdminProductosIdRoute: typeof AdminProductosIdRoute
  AdminProductosNuevoRoute: typeof AdminProductosNuevoRoute
  AdminProductosIndexRoute: typeof AdminProductosIndexRoute
}

const AdminProductosRouteChildren: AdminProductosRouteChildren = {
  AdminProductosIdRoute: AdminProductosIdRoute,
  AdminProductosNuevoRoute: AdminProductosNuevoRoute,
  AdminProductosIndexRoute: AdminProductosIndexRoute,
}

const AdminProductosRouteWithChildren = AdminProductosRoute._addFileChildren(
  AdminProductosRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminCuponesRoute: typeof AdminCuponesRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRouteWithChildren
  AdminReportesRoute: typeof AdminReportesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminCuponesRoute: AdminCuponesRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRouteWithChildren,
  AdminReportesRoute: AdminReportesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
